import torch
from transformers import AutoTokenizer
from experiment import CustomTrainer, GRPOConfig, reward_function # Import CustomTrainer and other necessary components

def probe_loss_function():
    # 1. Import the Trainer class from `experiment` (already done above)

    # 2. Create dummy torch inputs (batch size 2)
    model_name = "prajjwal1/bert-tiny" # Using a tiny model to avoid OOM
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.pad_token = tokenizer.eos_token

    # Dummy prompts and completions for the reward function and trainer
    dummy_prompts = ["Hello, what is the capital of France?", "Tell me a joke."]
    dummy_completions = ["The answer is Paris.", "Why did the scarecrow win an award? Because he was outstanding in his field!"]

    # Tokenize dummy inputs
    # The GRPOTrainer expects 'input_ids', 'attention_mask', 'labels' (for SFT loss if applicable),
    # and potentially 'rewards' if compute_loss is called directly with them.
    # For `compute_loss`, it typically generates completions internally or expects them.
    # Let's create inputs that mimic what the trainer would process.

    # For GRPO, the `inputs` dict usually contains 'input_ids', 'attention_mask',
    # and potentially 'rewards' and 'advantages' if pre-computed.
    # When `compute_loss` is called by the trainer, it internally handles generation
    # and reward calculation. We need to simulate the structure it expects.

    # Let's create dummy input_ids and attention_mask for the prompts
    # and also dummy generated responses and their rewards.
    # The `compute_loss` method in GRPOTrainer expects specific keys.
    # It usually takes `input_ids`, `attention_mask`, `rewards`, `advantages`, `logprobs`, etc.
    # We'll create a simplified version for a basic loss computation.

    # Tokenize prompts
    prompt_encodings = tokenizer(dummy_prompts, return_tensors="pt", padding=True, truncation=True, max_length=64)
    input_ids = prompt_encodings.input_ids
    attention_mask = prompt_encodings.attention_mask

    # Tokenize completions (these would typically be generated by the model)
    completion_encodings = tokenizer(dummy_completions, return_tensors="pt", padding=True, truncation=True, max_length=64)
    
    # For GRPO, the `compute_loss` method expects `rewards` and `advantages`
    # as well as `logprobs` from the current and old policy.
    # We'll create dummy tensors for these.
    
    # Dummy rewards (batch size 2)
    rewards = torch.tensor(reward_function(dummy_prompts, dummy_completions), dtype=torch.float32).unsqueeze(-1) # Shape (batch_size, 1)

    # Dummy logprobs (batch_size, sequence_length)
    # The sequence length should match the generated sequence length.
    # Let's assume a fixed sequence length for simplicity.
    dummy_sequence_length = completion_encodings.input_ids.shape[1]
    logprobs = torch.randn(2, dummy_sequence_length, dtype=torch.float32)
    old_logprobs = torch.randn(2, dummy_sequence_length, dtype=torch.float32)

    # Dummy values for `values` (value function output) and `old_values`
    values = torch.randn(2, dummy_sequence_length, dtype=torch.float32)
    old_values = torch.randn(2, dummy_sequence_length, dtype=torch.float32)

    # Dummy advantages (batch_size, sequence_length)
    # In a real scenario, advantages are computed from rewards and values.
    advantages = torch.randn(2, dummy_sequence_length, dtype=torch.float32)

    # Construct the `inputs` dictionary as expected by GRPOTrainer's compute_loss
    # This structure is based on how TRL's PPO/GRPO trainers pass data to compute_loss
    inputs = {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "rewards": rewards,
        "advantages": advantages,
        "logprobs": logprobs,
        "old_logprobs": old_logprobs,
        "values": values,
        "old_values": old_values,
        "labels": completion_encodings.input_ids, # Labels are often used for SFT part or masking
        "attention_mask_labels": completion_encodings.attention_mask,
    }
    
    # 3. Instantiate the Trainer
    config = GRPOConfig(
        output_dir="probe_runs",
        num_train_epochs=1,
        max_steps=1,
        per_device_train_batch_size=2,
        num_generations=1,
        max_completion_length=32,
        learning_rate=1e-5,
        clip_range_ratio=0.2,
        beta=0.0,
        # Set a dummy logging dir to avoid errors
        logging_dir="probe_runs/logs",
    )

    # Instantiate a dummy model for the trainer
    model = AutoModelForCausalLM.from_pretrained(model_name)

    trainer = CustomTrainer(
        model=model,
        args=config,
        train_dataset=None, # Not needed for direct compute_loss call
        processing_class=tokenizer,
        reward_funcs=[reward_function],
    )

    # 4. Run `trainer.compute_loss`
    # The `compute_loss` method expects `model` and `inputs`.
    # It also has `return_outputs` and `num_items_in_batch`.
    # We'll set `num_items_in_batch` to the batch size.
    loss, outputs = trainer.compute_loss(trainer.model, inputs, return_outputs=True, num_items_in_batch=2)

    # 5. Assert that the loss is a scalar and not NaN.
    assert isinstance(loss, torch.Tensor), f"Loss is not a torch.Tensor, but {type(loss)}"
    assert loss.dim() == 0, f"Loss is not a scalar, but has dimension {loss.dim()}"
    assert not torch.isnan(loss), "Loss is NaN"
    assert torch.isfinite(loss), "Loss is not finite (inf)"

    # Optionally, check some outputs if return_outputs is True
    assert 'loss' in outputs
    assert 'policy_loss' in outputs
    assert 'value_loss' in outputs

    # 6. Print "PROBE_SUCCESS" if it passes.
    print("PROBE_SUCCESS")

if __name__ == "__main__":
    # To run this probe, you might need to install `trl` and `datasets`
    # pip install trl datasets transformers torch
    from transformers import AutoModelForCausalLM # Import here to avoid circular dependency if experiment.py is run directly
    probe_loss_function()